trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  dockerRegistryServiceConnection: 'DockerHub'
  imageRepository: 'bhandhuvistu/medical-ai-platform'
  containerRegistry: 'docker.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'
  DOCKER_PASSWORD: $(DOCKER_PASSWORD)

stages:
  - stage: Build
    displayName: Build Maven Project
    jobs:
      - job: BuildJob
        steps:
          - task: Maven@3
            inputs:
              mavenPomFile: 'pom.xml'
              mavenOptions: '-Xmx3072m'
              javaHomeOption: 'JDKVersion'
              jdkVersionOption: '17'
              publishJUnitResults: true
              testResultsFiles: '**/surefire-reports/TEST-*.xml'

  - stage: BuildDocker
    displayName: Build and Push Docker Image
    dependsOn: Build
    condition: succeeded()
    jobs:
      - job: DockerBuild
        steps:
          - task: Docker@2
            displayName: Build and Push to Docker Hub
            inputs:
              command: buildAndPush
              repository: $(imageRepository)
              dockerfile: $(dockerfilePath)
              containerRegistry: $(dockerRegistryServiceConnection)
              tags: |
                $(tag)
                latest

  - stage: Deploy
    displayName: Deploy to Azure Container Instance
    dependsOn: BuildDocker
    condition: succeeded()
    jobs:
      - job: Deploy
        displayName: Deploy Container
        steps:
          - task: AzureCLI@2
            displayName: Update Container Instance
            inputs:
              azureSubscription: 'azure-app-service-connection'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az container create \
                  --resource-group DefaultResourceGroup-EUS \
                  --name my-app \
                  --image docker.io/bhandhuvistu/medical-ai-platform:$(tag) \
                  --cpu 1 \
                  --memory 1.5 \
                  --port 8080 \
                  --registry-login-server docker.io \
                  --registry-username bhandhuvistu \
                  --registry-password $(DOCKER_PASSWORD) \
                  --restart-policy OnFailure