trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  dockerImageName: 'medical-ai-platform:$(Build.BuildId)'

stages:
  - stage: Build
    jobs:
      - job: BuildJob
        steps:
          - task: Maven@3
            inputs:
              mavenPomFile: 'pom.xml'
              mavenOptions: '-Xmx3072m'
              javaHomeOption: 'JDKVersion'
              jdkVersionOption: '17'
              publishJUnitResults: true
              testResultsFiles: '**/surefire-reports/TEST-*.xml'
          
          - task: Docker@2
            inputs:
              command: 'build'
              Dockerfile: '**/Dockerfile'
              tags: '$(dockerImageName)'

  - stage: Test
    dependsOn: Build
    condition: succeeded()
    jobs:
      - job: TestJob
        steps:
          - script: echo "Testing docker image"
            displayName: 'Run Tests'
