server:
  port: 8080

spring:
  profiles:
    active: api
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    enabled: true

  ai:
    model:
      chat: none
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: llama3.1

  autoconfigure:
    exclude:
      - org.springframework.ai.model.ollama.autoconfigure.OllamaChatAutoConfiguration

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

aws:
  region: ap-south-2
  s3:
    bucket: med-ai-dev-data-762339788669-ap-south-2-an
    insecure-skip-ssl: true

ocr:
  enabled: false